"""Reading and writing a project directory.

A project is a directory of TOML, one file per concern, so a chemistry edit
does not touch the lines describing the grid. The files are a supported place
to work: you can edit one in a text editor, or generate a hundred variants from
a script, and open the result in the app.

    myproject.mup/
      project.toml     name, engine, units, time discretisation
      grid.toml
      flow.toml
      transport.toml
      run.toml
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from mupstudio.schema.project import SCHEMA_VERSION, Project
from mupstudio.store import toml_io

SUFFIX = ".mup"

# Which section of the model goes in which file. project.toml carries meta and
# time because a run's time axis is small and is what you check first.
SECTIONS: dict[str, tuple[str, ...]] = {
    "project.toml": ("meta", "time"),
    "grid.toml": ("grid",),
    "flow.toml": ("flow",),
    "transport.toml": ("transport",),
    "run.toml": ("run",),
}

GITIGNORE = """\
# Generated by mupstudio. Everything here can be rebuilt from the TOML files.
cache/
runs/
"""


class ProjectError(Exception):
    """The project could not be read."""


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def is_project(path: Path) -> bool:
    return (path / "project.toml").exists()


def load(directory: Path) -> Project:
    """Read a project, saying where the problem is when there is one.

    Errors name the file and the field, because these files are hand-edited and
    a bare pydantic traceback does not tell you which line to fix.
    """
    directory = Path(directory)
    if not is_project(directory):
        raise ProjectError(f"{directory} is not a project: no project.toml")

    merged: dict[str, Any] = {}
    for filename, sections in SECTIONS.items():
        path = directory / filename
        if not path.exists():
            continue
        try:
            content = toml_io.read(path)
        except Exception as error:
            raise ProjectError(f"{path.name} is not valid TOML: {error}") from error

        for section in sections:
            if section in content:
                merged[section] = content[section]

        unexpected = set(content) - set(sections)
        if unexpected:
            raise ProjectError(
                f"{path.name} has unexpected section(s) {', '.join(sorted(unexpected))}; "
                f"it should hold only {', '.join(sections)}"
            )

    version = int(merged.get("meta", {}).get("schema_version", SCHEMA_VERSION))
    if version > SCHEMA_VERSION:
        raise ProjectError(
            f"this project was written by a newer mupstudio (schema {version}, "
            f"this build reads {SCHEMA_VERSION}); upgrade to open it"
        )

    from mupstudio.schema import migrate

    merged = migrate.upgrade(merged, from_version=version)

    try:
        return Project.model_validate(merged)
    except ValidationError as error:
        raise ProjectError(_describe(error, directory)) from error


def save(directory: Path, project: Project, *, touch_modified: bool = True) -> Path:
    """Write a project, one file per section.

    The same project always produces the same bytes, so a save with no edits
    leaves version control untouched.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)

    if touch_modified:
        project = project.model_copy(deep=True)
        project.meta.created = project.meta.created or _now()
        project.meta.modified = _now()

    document = project.model_dump(mode="json", exclude_none=False)

    for filename, sections in SECTIONS.items():
        content = {section: document[section] for section in sections if section in document}
        toml_io.write(directory / filename, content)

    # Derived directories are regenerable, so they stay out of version control.
    (directory / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    return directory


def create(parent: Path, name: str, project: Project) -> Path:
    """Make a new project directory named after the project."""
    slug = "".join(
        character if character.isalnum() or character in "-_" else "-" for character in name
    )
    directory = Path(parent) / f"{slug}{SUFFIX}"
    if directory.exists():
        raise ProjectError(f"{directory} already exists")
    return save(directory, project)


def _describe(error: ValidationError, directory: Path) -> str:
    """Turn a validation error into something a person can act on."""
    lines = [f"{directory.name} has {error.error_count()} problem(s):"]
    for item in error.errors():
        location = ".".join(str(part) for part in item["loc"]) or "(root)"
        filename = _file_for(item["loc"])
        where = f"{filename} → {location}" if filename else location
        lines.append(f"  {where}: {item['msg']}")
    return "\n".join(lines)


def _file_for(location: tuple[Any, ...]) -> str | None:
    """Which file a field lives in, so the message points at the right one."""
    if not location:
        return None
    section = str(location[0])
    for filename, sections in SECTIONS.items():
        if section in sections:
            return filename
    return None
