[flow.properties]
icelltype = 0

[flow.properties.k]
kind = "constant"
value = 1.0

[flow.properties.porosity]
kind = "constant"
value = 0.32

[flow.properties.specific_storage]
kind = "constant"
value = 1e-05

[flow.properties.specific_yield]
kind = "constant"
value = 0.15

[flow.properties.starting_head]
kind = "constant"
value = 0.0

[[flow.packages]]
kind = "well"
id = "inflow"
[flow.packages.cells]
kind = "cells"
layers = [1]
rows = [1]
columns = [1]

[flow.packages.rate]
kind = "constant"
value = 0.16

[flow.packages.concentration]
kind = "constant"
value = 1.0


[[flow.packages]]
kind = "chd"
id = "outflow"
[flow.packages.cells]
kind = "cells"
layers = [1]
rows = [1]
columns = [50]

[flow.packages.head]
kind = "constant"
value = 0.0


[flow.solver]
outer_maximum = 50
inner_maximum = 100
outer_dvclose = 1e-06
inner_dvclose = 1e-06
complexity = "moderate"
